### ISSUE TITLE
handoffService and contractHost of chain bundle seem superfluous

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/cosmic-swingset#103]
vat-pixel exposes handoffService and contractHost
https://github.com/Agoric/cosmic-swingset/blob/654bd5eed6de2fdeedd8e26757c23590e4990bc9/lib/ag-solo/vats/vat-pixel.js#L53-L59

However, these are also exposed in bootstrap.js
https://github.com/Agoric/cosmic-swingset/blob/654bd5eed6de2fdeedd8e26757c23590e4990bc9/lib/ag-solo/vats/bootstrap.js#L49-L55

One of them feels superfluous. Probably the former

**Comment by Chris-Hibbert** [comment]
[vat-pixel](https://github.com/Agoric/cosmic-swingset/blob/0d6fa9e1e0e255c595a86710357cfcb58b400ce7/lib/ag-solo/vats/vat-pixel.js#L45) now has 
```
  async function createPixelBundle(_nickname) {
    const gallery = sharedGalleryUserFacet;
    const purse = await sharedDustAssay.makeEmptyPurse();
    const chainBundle = {
      gallery,
      canvasStatePublisher,
    };
    return { purse, bundle: harden(chainBundle) };
  }
```

The dust purse is returned separately from the chain bundle so it's easier to add to the wallet.

[Bootstrap has](https://github.com/Agoric/cosmic-swingset/blob/master/lib/ag-solo/vats/bootstrap.js#L101):

```
            const bundle = harden({
              ...pixelBundle,
              chainTimerService,
              sharingService,
              contractHost,
              registrar,
              zoe,
            });
```
And after adding the dust purse to `purses`, which contains the canonical moola and simolean purses, returns purses and bundle.

```
            return harden({ purses, bundle });
```

**Comment by warner** [comment]
in the old repo. this was cosmic-swingset issue 103
