### ISSUE TITLE
first provision works, the rest don't

### ISSUE THREAD

**Issue by michaelfig** [Agoric/cosmic-swingset#18]
Hi @warner,

With the code in master, I can provision the first ag-solo node on the testnet (!)  However, the next time and all subsequent times I provision with a different public key, it fails with:

```
olo[26551]: new block on da77b47573c1432e18ff3a6650fcd57e5219e49eec80d40b411935a49177519b, fetching mailbox
Jun 10 22:11:16 ag-chain-cosmos-mfig-digitalocean1-node0 ag-solo[26551]:  helper said: {"value":"{\"outbox\":[], \"ack\":0}"}
Jun 10 22:11:20 ag-chain-cosmos-mfig-digitalocean1-node0 ag-solo[26551]: cs[comms].dispatch.deliver 0.addEgress -> 35
Jun 10 22:11:20 ag-chain-cosmos-mfig-digitalocean1-node0 ag-solo[26551]: doProcess: vat[comms][0].addEgress dispatch failed: Error: kernel-import-13 already exists in clist Error: kernel-import-13 already exists in clist
Jun 10 22:11:20 ag-chain-cosmos-mfig-digitalocean1-node0 ag-solo[26551]:     at checkIfAlreadyExists (eval at <anonymous> (eval at createScopedEvaluatorFactory (/usr/src/ag-chain-cosmos/node_modules/ses/dist/ses.cjs.js:1:1)), <anonymous>:1288:13)
Jun 10 22:11:20 ag-chain-cosmos-mfig-digitalocean1-node0 ag-solo[26551]:     at Object.add (eval at <anonymous> (eval at createScopedEvaluatorFactory (/usr/src/ag-chain-cosmos/node_modules/ses/dist/ses.cjs.js:1:1)), <anonymous>:1376:5)
Jun 10 22:11:20 ag-chain-cosmos-mfig-digitalocean1-node0 ag-solo[26551]:     at addEgress (eval at <anonymous> (eval at createScopedEvaluatorFactory (/usr/src/ag-chain-cosmos/node_modules/ses/dist/ses.cjs.js:1:1)), <anonymous>:1552:18)
Jun 10 22:11:20 ag-chain-cosmos-mfig-digitalocean1-node0 ag-solo[26551]:     at handleCommsController (eval at <anonymous> (eval at createScopedEvaluatorFactory (/usr/src/ag-chain-cosmos/node_modules/ses/dist/ses.cjs.js:1:1)), <anonymous>:1616:14)
Jun 10 22:11:20 ag-chain-cosmos-mfig-digitalocean1-node0 ag-solo[26551]:     at Object.deliver (eval at <anonymous> (eval at createScopedEvaluatorFactory (/usr/src/ag-chain-cosmos/node_modules/ses/dist/ses.cjs.js:1:1)), <anonymous>:2016:24)
Jun 10 22:11:20 ag-chain-cosmos-mfig-digitalocean1-node0 ag-solo[26551]:     at eval (eval at <anonymous> (eval at createScopedEvaluatorFactory (/usr/src/ag-chain-cosmos/node_modules/ses/dist/ses.cjs.js:1:1)), <anonymous>:3023:27)
Jun 10 22:11:21 ag-chain-cosmos-mfig-digitalocean1-node0 ag-solo[26551]: deliver {}
Jun 10 22:11:22 ag-chain-cosmos-mfig-digitalocean1-node0 ag-solo[26551]: new block on da77b47573c1432e18ff3a6650fcd57e5219e49eec80d40b411935a49177519b, fetching mailbox
Jun 10 22:11:22 ag-chain-cosmos-mfig-digitalocean1-node0 ag-solo[26551]:  helper said: {"value":"{\"outbox\":[], \"ack\":0}"}
Jun 10 22:11:27 ag-chain-cosmos-mfig-digitalocean1-node0 ag-solo[265
```

The code that did this is in `lib/ag-solo/vats/vat-provisioning.js`, in the `pleaseProvision` function.  This is deep in the innards of SwingSet, so I'm not sure how to go about debugging it.

We're close!  Now rather than failing all the time, I need to bump the testnet before it will work again.

**Comment by warner** [comment]
Hmm. @katelynsills , do you know offhand if the commsSlots code maybe can't tolerate the same object being added as an egress multiple times? We have table entries for translation in both directions, but there should be a separate table for each target (so in the outbound direction we first find out where we're sending the reference, then we look the reference up in a table specific to that remote machine, adding it if necessary)

**Comment by warner** [comment]
I believe the line that fails is the call to `checkIfAlreadyExists` in `add()` in CLists.js, and I suspect that the `kernelToMeKey` is insufficiently unique. The key needs to include `otherMachineName`, not just the kernel-provided data.

**Comment by michaelfig** [comment]
That fits with my analysis.  I can make a PR in the next few hours.

**Comment by katelynsills** [comment]
Brian, you're right that [`checkIfAlreadyExists`](https://github.com/Agoric/SwingSet/blob/1829691039cc4ff0b8a6b7996888ec8fa2fbbe55/src/kernel/commsSlots/state/CLists.js#L14) does not allow the same kernelSlot to be stored again (enforced by the [`||`](https://github.com/Agoric/SwingSet/blob/1829691039cc4ff0b8a6b7996888ec8fa2fbbe55/src/kernel/commsSlots/state/CLists.js#L17) on line 17). At first, I thought this was a mistake, and we could simply make it an `&&`, but after looking into it, I think it's currently necessary based on how things are currently architected. 

If you look at [line 85 of commsSlots](https://github.com/Agoric/SwingSet/blob/1829691039cc4ff0b8a6b7996888ec8fa2fbbe55/src/kernel/commsSlots/commsSlots.js#L85), we only know the target of the message in kernelSlot form, and we have no idea which machine to send the message to until we get the machine info from the clist by using the kernelSlot as the key. So, the clist implementation cannot depend on knowing the `otherMachineName` if you only know the kernelSlot, so we cannot include `otherMachineName` in the `kernelToMeKey`. 

If we change the `||` in `checkIfAlreadyExists` to an `&&`, that will allow us to store the same information from multiple machines, but it will overwrite, so if a kernelSlot maps to machine0, and then we add another entry for the same kernelSlot for machine1, the kernelSlot will map to machine1. 

So, I think instead of including the machineName in the kernelSlot as stored, we actually need to add a layer of flexibility and allow a kernelSlot to map to a *list* of `outgoingWireMessages` rather than one. I can probably get to that this morning before my flight, unless you're already going on this @michaelfig. 

Hope that helps!

**Comment by michaelfig** [comment]
Thanks @katelynsills, I'd appreciate it if you could do this!

**Comment by katelynsills** [comment]
@michaelfig @warner I made a PR here that should fix this: https://github.com/Agoric/SwingSet/pull/78

**Comment by michaelfig** [comment]
Thanks, @katelynsills.  I merged the PR, and will test it on the testnet, then maybe @warner can cut an NPM release if it works.

**Comment by warner** [comment]
The way this works in PlaygroundVat and Foolscap is:

* the target of the outgoing message (always an ingress) gets looked up in a single table, and gets mapped to a remote machine and an egress index on that machine
* now that we know the remote machine, all other argument slots are mapped through a table that is specific to that remote machine. Every argument slot is either an ingress (from some machine, not necessarily the one to which the message is headed) or an egress (one of our own). In SwingSet, each ingess will appear in the vat as an export towards the kernel, and each egress will appear as an import from the kernel.
  * any ingress references pointing at the remote machine are rewritten as "your egress", using the same index
  * any ingress references pointed elsewhere require a three-party handoff, so will be rejected until we implement those
  * any egress refs get looked up in a per-target table, and mapped to a "your ingress" with some index that we allocate (if we can't find it in the table already)

So I think the `kernelSlot` -> `outgoingWireMessage` mapping is really (`kernelSlot`, `targetMachine`) -> `outgoingWireMessage`. Mapping it to a list of `outgoingWireMessages` would require searching through that list to find one that matches `targetMachine`, when it should be a direct lookup.

**Comment by katelynsills** [comment]
> So I think the `kernelSlot` -> `outgoingWireMessage` mapping is really (`kernelSlot`, `targetMachine`) -> `outgoingWireMessage`. Mapping it to a list of `outgoingWireMessages` would require searching through that list to find one that matches `targetMachine`, when it should be a direct lookup.

I didn't correct my original mention of a list in this thread, but the PR in https://github.com/Agoric/SwingSet/pull/78 does actually use a map to do a direct lookup. 

Given that, is there any functionality that you think we're missing with our current approach? I'm rushing out the door but will take some time to dive into your description of PlaygroundVat/Foolscap later today.

**Comment by warner** [comment]
Ah, if it's using a Map (or equivalent), that sounds about right. I'll look at the code. Thanks!

**Comment by michaelfig** [comment]
@warner, this code works well for me.  Please consider making new @agoric/swingset-vat release so we can use it directly in cosmic-swingset.

**Comment by warner** [comment]
The patch has some problems, but I don't think they'll interfere with this week's work, so I just made the 0.0.13 release of SwingSet. @michaelfig, please close this once we've updated cosmic-swingset to use 0.0.13 and we've verified that the testnet can handle multiple provisionings.

**Comment by michaelfig** [comment]
Bumped, verified, and pushed to testnet.

**Comment by warner** [comment]
in the old repo. this was cosmic-swingset issue 18
