### ISSUE TITLE
signing isn't working yet

### ISSUE THREAD

**Issue by warner** [Agoric/cosmic-swingset#3]
Here's the (convoluted) sequence to get the chain and the solo node set up:

(it assumes `ag-chain-cosmos` is on $PATH)

```
# ag-chain-cosmos init --chain-id agoric
# bin/ag-solo init t1
# ag-chain-cosmos add-genesis-account `cat t1/ag-cosmos-helper-address` 1000agtoken
# ag-chain-cosmos start
# make set-local-gci-ingress
# (cd t1 && ../bin/ag-solo start)
```

Then, once the ag-solo node gets started (wait until it says "deliverInbound" once or two), launch a browser at `localhost:8000`, and type `E(home.chain).getBalance()` into the text box, and hit the Eval button.

That will cause the solo node to try and sent a message to the chain (`home.chain` is a Presence pointing at an egress of the chain). The code in `lib/ag-solo/chain-cosmos-sdk.js` will fetch the account/sequence number for the ag-solo's keypair (address is in t1/ag-cosmos-helper-address), then POST the transaction body to the REST server's `/swingset/mailbox` endpoint.

I'm not sure the body is getting signed, but I'm not sure how to tell.

**Comment by warner** [comment]
Note: modifying the ag-solo code and then re-running `ag-solo start`, without resetting everything, runs into other problems, because our persistence is currently broken. So the `ag-solo` side throws exceptions about "historical inaccuracy in replay-fulfillToPresence". And when you delete `t1` and rebuild the ag-solo node, that erases the keypair, so the chain has to be rebuilt as well.

**Comment by michaelfig** [comment]
I'm getting a missing `./state/vatState`:

```
Michael-Macbook-680:cosmic-swingset michael$ ag-chain-cosmos init --chain-id agoric
-Starting Node
/Users/michael/agoric/cosmic-swingset/node_modules/@agoric/swingset-vat/src/kernel/vatManager.js:1
Error: Cannot find module './state/vatState'
Require stack:
- /Users/michael/agoric/cosmic-swingset/node_modules/@agoric/swingset-vat/src/kernel/vatManager.js
- /Users/michael/agoric/cosmic-swingset/node_modules/@agoric/swingset-vat/src/kernel/kernel.js
- /Users/michael/agoric/cosmic-swingset/node_modules/@agoric/swingset-vat/src/kernel/index.js
- /Users/michael/agoric/cosmic-swingset/node_modules/@agoric/swingset-vat/src/controller.js
- /Users/michael/agoric/cosmic-swingset/node_modules/@agoric/swingset-vat/src/index.js
- /Users/michael/agoric/cosmic-swingset/node_modules/@agoric/swingset-vat/src/main.js
- /Users/michael/agoric/cosmic-swingset/lib/launch-chain.js
- /Users/michael/agoric/cosmic-swingset/lib/ag-chain-cosmos
    at Object.<anonymous> (/Users/michael/agoric/cosmic-swingset/node_modules/@agoric/swingset-vat/src/kernel/vatManager.js:1)
Michael-Macbook-680:cosmic-swingset michael$ find . -name 'vatState*'
Michael-Macbook-680:cosmic-swingset michael$ 
```

**Comment by michaelfig** [comment]
That's my error: I had to reset the esm cache:
```
rm -rf node_modules/\@agoric/swingset-vat/node_modules/.cache
```

**Comment by warner** [comment]
Ugh, so it turns out that REST interface doesn't actually sign anything. It just emits a transaction record that the client must encode and sign themselves. The tutorial says it explicitly, somehow I missed that earlier: https://cosmos.network/docs/tutorial/rest.html#tx-handlers :

> Now define the buyName and setName transaction routes. Notice these aren't actually sending the transactions to buy and set names. That would require sending a password along with the request which would be a security issue. Instead these endpoints build and return each specific transaction which can then be signed in a secure manner and afterwards broadcast to the network using a standard endpoint like /txs.

It used to be possible to sign messages (there was even an endpoint for signing), but https://github.com/cosmos/cosmos-sdk/issues/3641 removed that ability back in Februrary. The issue has some discussion about the lack of encoding/signing tools in javascript and python.

@michaelfig where did you see the example that suggested `password` would be accepted? I'm guessing there are some SDK docs that are out of date, and they might appreciate us filing a bug. I found one place (the bottom of that tutorial page, which mentions a function named `clientrest.CompleteAndBroadcastTxREST` that doesn't appear anywhere in the SDK), but if we could find the place that says `password` and get it removed, it might save time for the next folks who go down this path.

Rats, I was expecting we could use the REST interface to do the signing, since our javascript code doesn't know how to do the signing itself (in fact it doesn't even have easy access to the private key, which is buried in some database somewhere that the CLI tool knows about).

So we either have to go back to shelling out to the helper process, or we need that FFI binding to the same code that the CLI functions are using. I'll start with the subprocess, since we already have code for that, but I'd love it if we could invoke it more directly.

**Comment by warner** [comment]
in the old repo. this was cosmic-swingset issue 3
