### ISSUE TITLE
provisioning code? requirements?

### ISSUE THREAD

**Issue by dckc** [Agoric/cosmic-swingset#30]
I tried to kick the tires today... I got as far as:

```
~/projects/agoric/cosmic-swingset$ SOLO_NAME=han ./docker/ag-setup-solo
solo [ 'init', 'han', '--webhost=0.0.0.0', '--webport=8000' ]
key generated, now extracting address
ag-solo initialized in han
HTTP/WebSocket will listen on 0.0.0.0:8000
Run '/usr/local/bin/ag-solo start' to start the vat machine
Provisioning code: 
```

I don't understand what "a public testnet provisioning page" refers to.

Is kicking the tires from my desktop expected to work?

If I need root, a Vagrantfile would be nice.

I gather multi-node deployment with Terraform and AWS is the norm... am I reading that right?

**Comment by erights** [comment]
Also failed kicking tires.

After a fresh `git clone ...` I then failed at `npm install`

```
$ npm install

> cosmic-swingset@0.7.4 install /Users/markmiller/src/ongithub/agoric/cosmic-swingset
> node-gyp rebuild

  CC(target) Release/obj.target/nothing/node_modules/node-addon-api/src/nothing.o
  LIBTOOL-STATIC Release/nothing.a
  CXX(target) Release/obj.target/agcosmosdaemon/lib/agcosmosdaemon-node.o
../lib/agcosmosdaemon-node.cc:4:10: fatal error: 'libagcosmosdaemon.h' file not
      found
#include "libagcosmosdaemon.h"
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by erights** [comment]
Nevermind my comment above. No relevance to @dckc 's.

**Comment by erights** [comment]
I got past my previous problem. (I read ahead and found that I need to "make" first.) Now I'm facing the same problem as @dckc

**Comment by erights** [comment]
Hi @dckc FWIW, I succeeded at building and running my own, starting from the instructions at https://github.com/Agoric/cosmic-swingset#build-from-source (to which I just made some minor corrections). Still does not address your original issue.

**Comment by michaelfig** [comment]
Sorry I didn't see this issue until now.

The `ag-setup-solo` workflow (`scenario1` in @warner's terminology) assumes a publically-installed chain using `setup/ag-setup-cosmos bootstrap`.  This currently requires DigitalOcean credentials, but my next target is local Docker installs.

If you want to try out the solo vat to local chain, this is called `scenario2`.  You can do:
```
$ make scenario2-setup
$ make scenario2-run-chain
[and in another terminal...]
$ make scenario2-run-client
```
then connect to http://localhost:8000

The `scenario3` setup is local solo vat only, without testing the interaction with the chain nodes:
```
$ make scenario3-setup
$ make scenario3-run-client 
```

This will be better documented in the future.  There are too many READMEs.

**Comment by michaelfig** [comment]
When Agoric/cosmic-swingset#47 lands, we will have a better README.

I will look into creating a Vagrantfile soon, so that the Linux-or-Docker requirement for the provisioning service (ag-setup-cosmos) can be replaced with a Linux-or-Vagrant-or-Docker requirement.

Thanks for the pointer, @dckc.

**Comment by michaelfig** [comment]
Hi @dckc, the proliferation of READMEs has also been solved, so you can go directly to the [README.md](/Agoric/cosmic-swingset/tree/master/README.md) if you want to work directly from this repo.

You can also have a look at the new [cosmic-workspace](/Agoric/cosmic-workspace) repo for a slightly easier developer workflow, for which I recommend Vagrant.

**Comment by dtribble** [comment]
That sounds like you don’t have GO setup e.g. in your path. We should have the install provide a better warning of that

**Comment by dckc** [comment]
The workspace stuff thru `npm run build` seems to be working.

I'm struggling with: Scenario 1: your own local testnet (develop testnet provisioner).
`make scenario1-run-chain` failed initially, but after I realized I should `cd cosmic-swingset` first, it started doing something useful... but then it prompted me about node allocation.

I looked at the swingset README

"See Testnet Tutorial for more guidance." sets expectations that aren't really met. "Unless you're developing..." should be subordinated. (IOU a PR) But I suppose I can skip that bit...

It just says "Fill out the node placement options". Um. How? I guessed at docker, 2 nodes.

Then it failed with `permission denied while trying to connect to the Docker daemon socket`.

last few hundred lines of transcript: https://gist.github.com/dckc/957f5dec6ea2e62c898d4217127414d7

I'm using docker as my vagrant provider. (slick!) But evidently the docker clients inside the containers can't access the docker socket. Which is normal. Was I supposed to run the vagrant containers in privileged mode somehow?

**Comment by dckc** [comment]
May I have a public testnet provisioning code, please? (Is this the place to ask?)

If you want to send it to me by email, use dckc@madmode.com

**Comment by michaelfig** [comment]
We really should renumber the scenarios (or at least rearrange them), as the best order to try is currently scenario0, scenario3, scenario2, scenario1.

There is a public form you can fill out at https://testnet.agoric.com

Your patience is appreciated, as the provisioning process is a little clunky right now.  We'll get better at it.  Thanks.

**Comment by michaelfig** [comment]
The vagrant docker provider should have mounted your docker socket.  Since it's `permission denied` you could try adding your `vagrant` user to the appropriate group (use `ls -l /var/run/docker.sock` within Vagrant to see that), then `vagrant ssh` again.

What platform is your host running?

**Comment by dckc** [comment]
Ubuntu 18.04

**Comment by michaelfig** [comment]
I'm closing this issue as it is accumulating unrelated information.  The new README is more descriptive.

Please follow up in separate issues if you run into other problems.

**Comment by warner** [comment]
in the old repo. this was cosmic-swingset issue 30
