### ISSUE TITLE
upgrade to latest cosmos-sdk

### ISSUE THREAD

**Issue by warner** [Agoric/cosmic-swingset#46]
We're currently using [cosmos-sdk](https://github.com/cosmos/cosmos-sdk/) v0.33.0, as declared in our `go.mod` specification:

https://github.com/Agoric/cosmic-swingset/blob/396963cf180c315a7bb3e15dcbdf2e5da579bc3d/go.mod#L11

We should upgrade to the latest release, which is `v0.35.0` (and they're working on 0.36.0).

**Comment by warner** [comment]
I did a `make scenario2-setup` on that branch, using cosmos-sdk-0.35.0, and was able to send a few commands to the chain without problems (`tapFaucet` works, at least).

**Comment by michaelfig** [comment]
When I send a provisioning request, it is handled by the controller vat as follows:

```
Aug 01 00:01:36 ag-chain-cosmos-mfig-digitalocean1-node0 ag-solo[31160]: ag-cosmos-helper tx swingset deliver cosmos1huj4a4relyq90wrulg35s3dtvhtnasj56hv4hg [[[1,"{\"event\":\"send\",\"target\":{\"type\":\"your-egress\",\"id\":1},\"methodName\":\"pleaseProvision\",\"args\":[\"fofo\",\"cosmos1vxt53hypv846q0y8kc22q60e5tu6yvvnef3wv2\"],\"slots\":[],\"resultSlot\":{\"type\":\"your-resolver\",\"id\":3}}"]],0] --from ag-solo --yes --chain-id mfig-4.2.5 --output json --node tcp://xxx.yyy.zzz.www:26657 --home /home/ag-pserver/controller/ag-cosmos-helper-statedir
Aug 01 00:01:37 ag-chain-cosmos-mfig-digitalocean1-node0 ag-solo[31160]:  helper said: {"height":"0","txhash":"698B9921A854ECF0F1BE99DD184F54ABBFB3F4B0C0132B2FF60EA6DC2965B8FF","code":4,"raw_log":"{\"codespace\":\"sdk\",\"code\":4,\"message\":\"signature verification failed; verify correct account sequence and chain-id\"}"}
```

For whatever reason, the controller vat can't sign the message properly.  When I run the ag-cosmos-helper command manually it works.  If I do that soon enough (before the provisioning server times out), the provisioning succeeds.

I'm not sure how `ag-cosmos-helper` has changed.

**Comment by warner** [comment]
Maybe we aren't getting the provisioning node's key in place correctly (as an account in the genesis block)?

Also, maybe we need the provisioner node to wait for a block or two before trying to send anything to the chain?

**Comment by michaelfig** [comment]
This turns out that the `ag-cosmos-helper` command no longer waits for the sending of `1agmedallion` to the new address unless you add `--broadcast-mode block`.

**Comment by warner** [comment]
in the old repo. this was cosmic-swingset issue 46
