### ISSUE TITLE
In getting started, use object properties on home instead of the history array

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/cosmic-swingset#69]
[(source of the idea)](https://github.com/Agoric/Documentation/pull/3#commitcomment-34797825)

Current:

```
home.gallery!tapFaucet()
history[0]!getBalance()
history[0]!getUse()
history[2]!changeColorAll('#FF69B4')
```

Possible:

```
home.pixel = home.gallery!tapFaucet()
home.pixel!getBalance()
home.use = history.pixel!getUse()
home.use!changeColorAll('#FF69B4')
```

This makes the example more resilient in the face of make errors in typing the commands or wanting to do different commands in between

**Comment by erights** [comment]
Just FYI for now.

Once https://github.com/Agoric/realms-shim/pull/33 lands, we'll be able to support

```js
pixel = home.gallery!tapFaucet();
pixel!getBalance();
use = history.pixel!getUse();
use!changeColorAll('#FF69B4');
```

Btw, I added the needed semicolons. Never forget the semicolons!

**Comment by katelynsills** [comment]
> Btw, I added the needed semicolons. Never forget the semicolons!

Just wanted to point out that our REPL doesn't currently support semicolons, so we can't use them in the examples.

**Comment by michaelfig** [comment]
Actually, the REPL is now a script target evaluator instead if an expression evaluator, so semicolons are fine.

**Comment by katelynsills** [comment]
> Actually, the REPL is now a script target evaluator instead if an expression evaluator, so semicolons are fine.

Oh, excellent!

**Comment by michaelfig** [comment]
This is supported and part of the readme as of [v0.8.6](/Agoric/cosmic-swingset/tree/v0.8.6).

**Comment by warner** [comment]
in the old repo. this was cosmic-swingset issue 69
