### ISSUE TITLE
Lots of untracked files generated with make scenario1-run-chain

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/cosmic-swingset#87]
Running `make scenario1-run-chain` got me these new files not tracked by git:

```
.terraform/
ansible-playbook.sh
ansible.cfg
boot-tokens.txt
id_ecdsa
id_ecdsa.pub
network.txt
outputs.tf
placement-docker1.tf
vars.tf
```

Should these be added to `.gitignore`?

**Comment by michaelfig** [comment]
Actually, the Makefile should be fixed to put these in subdirectories.  I've created the PR for it.

**Comment by warner** [comment]
in the old repo. this was cosmic-swingset issue 87
