### ISSUE TITLE
"deliverInbound is not a function" error in make scenario2-run-client

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/cosmic-swingset#97]
With a fresh build on the [latest master](https://github.com/Agoric/cosmic-swingset/commit/226167d55d8a7fbf68438c402cf32b8bae57c156), i try scenario 2 and when trying the client, i get the following:

```sh
$ make scenario2-run-client BASE_PORT=8000
cd t1/8000 && ../../bin/ag-solo start --role=two_client
solo [ 'start', '--role=two_client' ]
adding HTTP/WS listener on 127.0.0.1:8000
Serving static files from /home/david/projects/cosmic-swingset/t1/8000/html
adding follower/sender for GCI 8db53f0f673acafe8783ee32b221ac8c18d905c9c033061e17653d2ac50dedb8
Listening on 127.0.0.1:8000
= loading config from basedir /home/david/projects/cosmic-swingset/t1/8000/vats
ignoring  bootstrap.js
ignoring  gci.js
ignoring  guess37-contract.js
ignoring  pubsub.js
ignoring  repl.js
ignoring  scratch.js
kernel.addDevice(mailbox)
kernel.addDevice(command)
= adding vat 'handoff' from /home/david/projects/cosmic-swingset/t1/8000/vats/vat-handoff.js
= adding vat 'host' from /home/david/projects/cosmic-swingset/t1/8000/vats/vat-host.js
new block on 8db53f0f673acafe8783ee32b221ac8c18d905c9c033061e17653d2ac50dedb8, fetching mailbox
ag-cosmos-helper query swingset mailbox cosmos1l38hwtac9r7yl9xsjz4p90wy507xzndh2x94a0 --chain-id agoric --output json --node tcp://127.0.0.1:26657 --home /home/david/projects/cosmic-swingset/t1/8000/ag-cosmos-helper-statedir
= adding vat 'http' from /home/david/projects/cosmic-swingset/t1/8000/vats/vat-http.js

 helper said: {"value":"\"{\\\"outbox\\\":[], \\\"ack\\\":0}\""}

Failed to fetch 8db53f0f673acafe8783ee32b221ac8c18d905c9c033061e17653d2ac50dedb8 mailbox: TypeError: deliverInbound is not a function
    at inbound (/home/david/projects/cosmic-swingset/lib/ag-solo/start.js:146:5)
    at /home/david/projects/cosmic-swingset/lib/ag-solo/chain-cosmos-sdk.js:305:11
= adding vat 'pixel' from /home/david/projects/cosmic-swingset/t1/8000/vats/vat-pixel.js
= adding vat 'provisioning' from /home/david/projects/cosmic-swingset/t1/8000/vats/vat-provisioning.js
= adding vat 'registry' from /home/david/projects/cosmic-swingset/t1/8000/vats/vat-registry.js
= adding vat 'uploads' from /home/david/projects/cosmic-swingset/t1/8000/vats/vat-uploads.js
= adding vat 'zoe' from /home/david/projects/cosmic-swingset/t1/8000/vats/vat-zoe.js
= adding vat 'vattp' from /home/david/projects/cosmic-swingset/node_modules/@agoric/swingset-vat/src/vats/vat-tp/vattp.js
127.0.0.1:52120[1]: new ws connection /
HTTP: POST /vat 500 1322 - 26.913 ms
TypeError: deliverInboundCommand is not a function
    at command (/home/david/projects/cosmic-swingset/lib/ag-solo/start.js:151:12)
    at /home/david/projects/cosmic-swingset/lib/ag-solo/web.js:65:5
    at Layer.handle [as handle_request] (/home/david/projects/cosmic-swingset/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/david/projects/cosmic-swingset/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/david/projects/cosmic-swingset/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/david/projects/cosmic-swingset/node_modules/express/lib/router/layer.js:95:5)
    at /home/david/projects/cosmic-swingset/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/david/projects/cosmic-swingset/node_modules/express/lib/router/index.js:335:12)
    at next (/home/david/projects/cosmic-swingset/node_modules/express/lib/router/index.js:275:10)
    at serveStatic (/home/david/projects/cosmic-swingset/node_modules/serve-static/index.js:75:16)
= adding vat 'comms' from /home/david/projects/cosmic-swingset/node_modules/@agoric/swingset-vat/src/vats/comms/index.js
127.0.0.1:52120[1]: client closed
= adding vat '_bootstrap' from /home/david/projects/cosmic-swingset/t1/8000/vats/bootstrap.js
loading bootstrap.js

(rest stripped)
```

Based on [the code](https://github.com/Agoric/cosmic-swingset/blob/226167d55d8a7fbf68438c402cf32b8bae57c156/lib/ag-solo/start.js#L143-L170) i feel it could be a race condition

When `connectToChain` is called, `inbound` is a function, but maybe `deliverInbound` is still `undefined`. I haven't looked at `connectToChain`, but maybe it calls its `inbound` argument at a time `deliverInbound` is still `undefined`

**Comment by michaelfig** [comment]
Yes, I've seen a couple of races with the SwingSet setup.

What is the severity: is the client usable after reloading, or is this a showstopper for you?

**Comment by DavidBruant** [comment]
> What is the severity: is the client usable after reloading, or is this a showstopper for you?

It is a showstopper. When i type `home` in the Pixel demo REPL, i get the "loading" promise/presence and it never resolves (or rather i give up after a very long time)

I tried to restart everything and the error came back each time (but that's a race condition, so what happens on my machine is of course not a universal experience)

**Comment by michaelfig** [comment]
Okay, thank you for your report.  I will work on resolving these (two!) races.

One workaround you can try is to close all your localhost:8000 browser windows and then restart that ag-solo.  Only when the ag-solo begins polling the chain should you open the browser.

**Comment by michaelfig** [comment]
I have some simple mitigations in place now.  Do note, however, that there are still races between starting a new chain node and starting ag-solos that use it.

You should not have any problems with current master, so long as you *first* start the chain, wait for it to commit a block, and *then* start your ag-solo.

Please close this issue if it works for you, otherwise, I'd be happy to investigate further.  The behaviour should have changed, though.

**Comment by DavidBruant** [comment]
I still have the same symptoms without the error thrown
My symptom is the following REPL:
```
command[0]  home
history[0] {"LOADING":[Promise]}
```

I feel like i was maybe wrong in my diagnosis thinking it was the race condition
I'm not sure whether i should close this issue to make a new one or keep this issue open

**Comment by DavidBruant** [comment]
I'm playing with a different contract and different `vat-pixel`. I thought the changes shouldn't influence, but maybe they do. I'll investigate on my end. In any case, with the pixel demo on current master, i see the following:

```
command[0] home
history[0] {"LOADING":[Promise],"gallery":[Presence o-50],"handoffService":[Presence o-51],"purse":[Presence o-52],"canvasStatePublisher":[Presence o-53],"contractHost":[Presence o-54],"handoff":[Presence o-55],"registry":[Presence o-56],"zoe":[Presence o-57],"uploads":[Presence o-58]}
```

I'm still surprised of the `"LOADING":[Promise]` though it now seems unrelated to my problem

**Comment by DavidBruant** [comment]
I got something working. I'm closing this issue for now
Thanks for taking the time to fix the race condition

**Comment by warner** [comment]
in the old repo. this was cosmic-swingset issue 97
